const fs = require('fs');
const path = require('path');

const targetFile = path.resolve('data/questions.js');

const ctcData = {
  // Test 7
  "q0511": { "translation": "Kiến trúc sư đã thiết kế tòa nhà.", "vocab": [ { "word": "architect", "type": "n.", "meaning": "kiến trúc sư" }, { "word": "design", "type": "v.", "meaning": "thiết kế" } ] },
  "q0512": { "translation": "Ngân sách có vẻ eo hẹp.", "vocab": [ { "word": "budget", "type": "n.", "meaning": "ngân sách" }, { "word": "tight", "type": "adj.", "meaning": "eo hẹp/chặt chẽ" } ] },
  "q0513": { "translation": "Lô hàng đã đến muộn.", "vocab": [ { "word": "cargo", "type": "n.", "meaning": "hàng hóa/lô hàng" }, { "word": "arrive", "type": "v.", "meaning": "đến nơi" } ] },
  "q0514": { "translation": "Ủy ban đã bổ nhiệm anh ấy làm quản lý dự án.", "vocab": [ { "word": "committee", "type": "n.", "meaning": "ủy ban" }, { "word": "appoint", "type": "v.", "meaning": "bổ nhiệm" } ] },
  "q0515": { "translation": "Nhà thầu đã ký vào bản hợp đồng.", "vocab": [ { "word": "contractor", "type": "n.", "meaning": "nhà thầu" }, { "word": "agreement", "type": "n.", "meaning": "hợp đồng/sự thỏa thuận" } ] },
  "q0516": { "translation": "Thuế suất đã giảm.", "vocab": [ { "word": "tax rate", "type": "n.", "meaning": "thuế suất" }, { "word": "drop", "type": "v.", "meaning": "giảm xuống/rơi" } ] },
  "q0517": { "translation": "Nhân viên hải quan đã kiểm tra hộ chiếu.", "vocab": [ { "word": "customs officer", "type": "n.", "meaning": "nhân viên hải quan" }, { "word": "passport", "type": "n.", "meaning": "hộ chiếu" } ] },
  "q0518": { "translation": "Lịch trình vẫn không thay đổi.", "vocab": [ { "word": "schedule", "type": "n.", "meaning": "lịch trình" }, { "word": "unchanged", "type": "adj.", "meaning": "không thay đổi" } ] },
  "q0519": { "translation": "Họ đã bầu cô ấy làm trưởng nhóm.", "vocab": [ { "word": "team leader", "type": "n.", "meaning": "trưởng nhóm" } ] },
  "q0520": { "translation": "Chuyên viên phân tích dữ liệu đã xuất tệp.", "vocab": [ { "word": "analyst", "type": "n.", "meaning": "chuyên viên phân tích" }, { "word": "export", "type": "v.", "meaning": "xuất (dữ liệu/hàng hóa)" } ] },
  "q0521": { "translation": "Nền kinh tế phục hồi chậm.", "vocab": [ { "word": "economy", "type": "n.", "meaning": "nền kinh tế" }, { "word": "recover", "type": "v.", "meaning": "phục hồi" } ] },
  "q0522": { "translation": "Các quy định mới có vẻ nghiêm ngặt.", "vocab": [ { "word": "regulation", "type": "n.", "meaning": "quy định" }, { "word": "strict", "type": "adj.", "meaning": "nghiêm ngặt" } ] },
  "q0523": { "translation": "Người giám sát đã tìm thấy lỗi.", "vocab": [ { "word": "supervisor", "type": "n.", "meaning": "người giám sát" }, { "word": "error", "type": "n.", "meaning": "lỗi" } ] },
  "q0524": { "translation": "Khách hàng cho rằng chi phí cao.", "vocab": [ { "word": "client", "type": "n.", "meaning": "khách hàng" }, { "word": "consider", "type": "v.", "meaning": "xem xét/coi là" } ] },
  "q0525": { "translation": "Các công nhân đã bắt đầu sớm.", "vocab": [ { "word": "worker", "type": "n.", "meaning": "công nhân" } ] },
  "q0526": { "translation": "Kế toán đã xác minh hóa đơn.", "vocab": [ { "word": "accountant", "type": "n.", "meaning": "kế toán" }, { "word": "verify", "type": "v.", "meaning": "xác minh" }, { "word": "invoice", "type": "n.", "meaning": "hóa đơn" } ] },
  "q0527": { "translation": "Lô hàng trông có vẻ nặng.", "vocab": [ { "word": "shipment", "type": "n.", "meaning": "lô hàng" }, { "word": "heavy", "type": "adj.", "meaning": "nặng" } ] },
  "q0528": { "translation": "Giám đốc đã chỉ định anh ấy làm kỹ sư trưởng.", "vocab": [ { "word": "lead engineer", "type": "n.", "meaning": "kỹ sư trưởng" } ] },
  "q0529": { "translation": "Thị trường sụp đổ đột ngột.", "vocab": [ { "word": "market", "type": "n.", "meaning": "thị trường" }, { "word": "crash", "type": "v.", "meaning": "sụp đổ/va chạm" } ] },
  "q0530": { "translation": "Hệ thống đã xử lý dữ liệu.", "vocab": [ { "word": "process", "type": "v.", "meaning": "xử lý" }, { "word": "data", "type": "n.", "meaning": "dữ liệu" } ] },
  "q0531": { "translation": "Việc giao hàng tỏ ra khó khăn.", "vocab": [ { "word": "delivery", "type": "n.", "meaning": "việc giao hàng" }, { "word": "prove", "type": "v.", "meaning": "chứng tỏ/tỏ ra" } ] },
  "q0532": { "translation": "Ban điều hành đã giữ bí mật chiến lược.", "vocab": [ { "word": "board", "type": "n.", "meaning": "ban điều hành" }, { "word": "strategy", "type": "n.", "meaning": "chiến lược" }, { "word": "secret", "type": "adj.", "meaning": "bí mật" } ] },
  "q0533": { "translation": "Thuế nhập khẩu đã tăng.", "vocab": [ { "word": "import duties", "type": "n.", "meaning": "thuế nhập khẩu" }, { "word": "increase", "type": "v.", "meaning": "tăng" } ] },
  "q0534": { "translation": "Các nhà đầu tư đã xem xét danh mục đầu tư.", "vocab": [ { "word": "investor", "type": "n.", "meaning": "nhà đầu tư" }, { "word": "portfolio", "type": "n.", "meaning": "danh mục đầu tư" } ] },
  "q0535": { "translation": "Dự án đã trở nên thành công.", "vocab": [ { "word": "project", "type": "n.", "meaning": "dự án" }, { "word": "successful", "type": "adj.", "meaning": "thành công" } ] },
  // Test 6
  "q0486": { "translation": "Nhân viên hải quan đã kiểm tra hàng hóa.", "vocab": [ { "word": "inspector", "type": "n.", "meaning": "người kiểm tra" }, { "word": "cargo", "type": "n.", "meaning": "hàng hóa" } ] },
  "q0487": { "translation": "Nhân viên hải quan đã kiểm tra hàng hóa.", "vocab": [ { "word": "inspector", "type": "n.", "meaning": "người kiểm tra" }, { "word": "cargo", "type": "n.", "meaning": "hàng hóa" } ] },
  "q0488": { "translation": "Chính sách thuế vẫn không đổi.", "vocab": [ { "word": "tax policy", "type": "n.", "meaning": "chính sách thuế" }, { "word": "unchanged", "type": "adj.", "meaning": "không đổi" } ] },
  "q0489": { "translation": "Thuật toán đã vận hành trôi chảy.", "vocab": [ { "word": "algorithm", "type": "n.", "meaning": "thuật toán" }, { "word": "smoothly", "type": "adv.", "meaning": "một cách trôi chảy" } ] },
  "q0490": { "translation": "Quản lý dự án cho rằng lịch trình không thực tế.", "vocab": [ { "word": "unrealistic", "type": "adj.", "meaning": "không thực tế" } ] },
  "q0491": { "translation": "Các kỹ sư đã phân tích dữ liệu.", "vocab": [ { "word": "engineer", "type": "n.", "meaning": "kỹ sư" }, { "word": "analyze", "type": "v.", "meaning": "phân tích" } ] },
  "q0492": { "translation": "Công trường xây dựng trông có vẻ nguy hiểm.", "vocab": [ { "word": "hazardous", "type": "adj.", "meaning": "nguy hiểm" }, { "word": "construction site", "type": "n.", "meaning": "công trường" } ] },
  "q0493": { "translation": "Nhóm nghiên cứu đánh giá việc nhập khẩu thành công.", "vocab": [ { "word": "consider", "type": "v.", "meaning": "đánh giá/xem xét" }, { "word": "successful", "type": "adj.", "meaning": "thành công" } ] },
  "q0494": { "translation": "Những quả táo tươi đã đến vào ngày hôm qua.", "vocab": [ { "word": "fresh", "type": "adj.", "meaning": "tươi" }, { "word": "arrive", "type": "v.", "meaning": "đến" } ] },
  "q0495": { "translation": "Chuỗi cung ứng đã bị gián đoạn.", "vocab": [ { "word": "supply chain", "type": "n.", "meaning": "chuỗi cung ứng" }, { "word": "disrupt", "type": "v.", "meaning": "gián đoạn" } ] },
  "q0496": { "translation": "Hàng tồn kho đã giảm dần đều.", "vocab": [ { "word": "inventory", "type": "n.", "meaning": "hàng tồn kho" }, { "word": "steadily", "type": "adv.", "meaning": "đều đặn/vững chắc" } ] },
  "q0497": { "translation": "Phần mềm đã tạo ra một biểu đồ trực quan.", "vocab": [ { "word": "generate", "type": "v.", "meaning": "tạo ra" }, { "word": "visual chart", "type": "n.", "meaning": "biểu đồ trực quan" } ] },
  "q0498": { "translation": "Các giám đốc bổ nhiệm anh ấy làm chuyên viên phân tích trưởng.", "vocab": [ { "word": "appoint", "type": "v.", "meaning": "bổ nhiệm" }, { "word": "lead analyst", "type": "n.", "meaning": "chuyên viên phân tích trưởng" } ] },
  "q0499": { "translation": "Tàu chở hàng đã khởi hành sớm.", "vocab": [ { "word": "freight train", "type": "n.", "meaning": "tàu chở hàng" }, { "word": "depart", "type": "v.", "meaning": "khởi hành" } ] },
  "q0500": { "translation": "Dự báo kinh tế có vẻ bi quan.", "vocab": [ { "word": "economic forecast", "type": "n.", "meaning": "dự báo kinh tế" }, { "word": "pessimistic", "type": "adj.", "meaning": "bi quan" } ] },
  "q0501": { "translation": "Thuế nhập khẩu đã tăng nhẹ.", "vocab": [ { "word": "import tax", "type": "n.", "meaning": "thuế nhập khẩu" }, { "word": "slightly", "type": "adv.", "meaning": "một cách nhẹ nhàng/không đáng kể" } ] },
  "q0502": { "translation": "Các thanh tra viên phát hiện hàng hóa bị hư hỏng.", "vocab": [ { "word": "inspector", "type": "n.", "meaning": "thanh tra viên" }, { "word": "damage", "type": "v.", "meaning": "làm hỏng" } ] },
  "q0503": { "translation": "Doanh nghiệp đã mở rộng nhanh chóng.", "vocab": [ { "word": "expand", "type": "v.", "meaning": "mở rộng" }, { "word": "rapidly", "type": "adv.", "meaning": "một cách nhanh chóng" } ] },
  "q0504": { "translation": "Đội ngũ hậu cần đã giải quyết vấn đề.", "vocab": [ { "word": "logistics", "type": "n.", "meaning": "hậu cần" }, { "word": "solve", "type": "v.", "meaning": "giải quyết" } ] },
  "q0505": { "translation": "Cơ sở dữ liệu hoạt động hiệu quả.", "vocab": [ { "word": "database", "type": "n.", "meaning": "cơ sở dữ liệu" }, { "word": "efficiently", "type": "adv.", "meaning": "một cách hiệu quả" } ] },
  "q0506": { "translation": "Người giám sát đã làm rõ các quy tắc.", "vocab": [ { "word": "supervisor", "type": "n.", "meaning": "người giám sát" }, { "word": "clear", "type": "adj.", "meaning": "rõ ràng" } ] },
  "q0507": { "translation": "Các nhà phân tích đã dự đoán một sự thay đổi thị trường.", "vocab": [ { "word": "predict", "type": "v.", "meaning": "dự đoán" }, { "word": "market shift", "type": "n.", "meaning": "sự thay đổi thị trường" } ] },
  "q0508": { "translation": "Quy trình làm việc có vẻ hợp lý.", "vocab": [ { "word": "workflow", "type": "n.", "meaning": "quy trình làm việc" }, { "word": "logical", "type": "adj.", "meaning": "hợp lý" } ] },
  "q0509": { "translation": "Cơ quan quản lý cảng đã chấp thuận lô hàng.", "vocab": [ { "word": "port authority", "type": "n.", "meaning": "cơ quan quản lý cảng" }, { "word": "approve", "type": "v.", "meaning": "chấp thuận" } ] },
  "q0510": { "translation": "Thủ tục hải quan tỏ ra phức tạp.", "vocab": [ { "word": "customs procedure", "type": "n.", "meaning": "thủ tục hải quan" }, { "word": "complicated", "type": "adj.", "meaning": "phức tạp" } ] },
  // Test 5
  "q0461": { "translation": "Nhà đầu tư đã mua cổ phiếu.", "vocab": [ { "word": "investor", "type": "n.", "meaning": "nhà đầu tư" }, { "word": "share", "type": "n.", "meaning": "cổ phiếu" } ] },
  "q0462": { "translation": "Máy bay chở hàng khởi hành an toàn.", "vocab": [ { "word": "cargo plane", "type": "n.", "meaning": "máy bay chở hàng" }, { "word": "depart", "type": "v.", "meaning": "khởi hành" } ] },
  "q0463": { "translation": "Người giám sát có vẻ rất bận rộn.", "vocab": [ { "word": "supervisor", "type": "n.", "meaning": "người giám sát" }, { "word": "busy", "type": "adj.", "meaning": "bận rộn" } ] },
  "q0464": { "translation": "Họ cho rằng chính sách không công bằng.", "vocab": [ { "word": "consider", "type": "v.", "meaning": "đánh giá/xem xét" }, { "word": "unfair", "type": "adj.", "meaning": "không công bằng" } ] },
  "q0465": { "translation": "Thư ký đã trả lời các email.", "vocab": [] },
  "q0466": { "translation": "Thiết bị mới hoạt động hoàn hảo.", "vocab": [ { "word": "equipment", "type": "n.", "meaning": "thiết bị" }, { "word": "perfectly", "type": "adv.", "meaning": "hoàn hảo" } ] },
  "q0467": { "translation": "Văn phòng hôm nay vẫn yên tĩnh.", "vocab": [ { "word": "remain", "type": "v.", "meaning": "vẫn còn" }, { "word": "quiet", "type": "adj.", "meaning": "yên tĩnh" } ] },
  "q0468": { "translation": "Hội đồng bầu cô ấy làm CEO.", "vocab": [ { "word": "board", "type": "n.", "meaning": "hội đồng" }, { "word": "elect", "type": "v.", "meaning": "bầu chọn" } ] },
  "q0469": { "translation": "Nhóm đã đạt được mục tiêu.", "vocab": [ { "word": "achieve", "type": "v.", "meaning": "đạt được" }, { "word": "goal", "type": "n.", "meaning": "mục tiêu" } ] },
  "q0470": { "translation": "Chi phí vận chuyển tăng nhanh.", "vocab": [ { "word": "shipping cost", "type": "n.", "meaning": "chi phí vận chuyển" }, { "word": "rapidly", "type": "adv.", "meaning": "nhanh chóng" } ] },
  "q0471": { "translation": "Bản đề xuất nghe có vẻ rất thú vị.", "vocab": [ { "word": "proposal", "type": "n.", "meaning": "bản đề xuất" }, { "word": "interesting", "type": "adj.", "meaning": "thú vị" } ] },
  "q0472": { "translation": "Quản lý thấy bản báo cáo chưa hoàn chỉnh.", "vocab": [ { "word": "manager", "type": "n.", "meaning": "quản lý" }, { "word": "incomplete", "type": "adj.", "meaning": "chưa hoàn chỉnh" } ] },
  "q0473": { "translation": "Chúng tôi đã ký hợp đồng cho thuê.", "vocab": [ { "word": "sign", "type": "v.", "meaning": "ký kết" }, { "word": "lease agreement", "type": "n.", "meaning": "hợp đồng thuê" } ] },
  "q0474": { "translation": "Mất điện một lần nữa.", "vocab": [ { "word": "power", "type": "n.", "meaning": "điện/năng lượng" }, { "word": "fail", "type": "v.", "meaning": "thất bại/hỏng" } ] },
  "q0475": { "translation": "Tình hình hiện tại có vẻ ổn định.", "vocab": [ { "word": "situation", "type": "n.", "meaning": "tình hình" }, { "word": "stable", "type": "adj.", "meaning": "ổn định" } ] },
  "q0476": { "translation": "Ủy ban chỉ định anh ấy làm giám đốc.", "vocab": [ { "word": "committee", "type": "n.", "meaning": "ủy ban" }, { "word": "name", "type": "v.", "meaning": "chỉ định" } ] },
  "q0477": { "translation": "Phòng ban đã thuê nhân viên mới.", "vocab": [ { "word": "department", "type": "n.", "meaning": "phòng ban" }, { "word": "hire", "type": "v.", "meaning": "thuê" } ] },
  "q0478": { "translation": "Các cuộc đàm phán tiếp tục trong hòa bình.", "vocab": [ { "word": "negotiation", "type": "n.", "meaning": "sự đàm phán" }, { "word": "peacefully", "type": "adv.", "meaning": "hòa bình" } ] },
  "q0479": { "translation": "Quyết định cuối cùng thật khó khăn.", "vocab": [ { "word": "final decision", "type": "n.", "meaning": "quyết định cuối cùng" }, { "word": "difficult", "type": "adj.", "meaning": "khó khăn" } ] },
  "q0480": { "translation": "Sự chậm trễ làm hành khách giận dữ.", "vocab": [ { "word": "delay", "type": "n.", "meaning": "sự chậm trễ" }, { "word": "furious", "type": "adj.", "meaning": "giận dữ" } ] },
  "q0481": { "translation": "Kế toán đã chuẩn bị hóa đơn.", "vocab": [ { "word": "accountant", "type": "n.", "meaning": "kế toán" }, { "word": "invoice", "type": "n.", "meaning": "hóa đơn" } ] },
  "q0482": { "translation": "Chuông báo vang lên ồn ào.", "vocab": [ { "word": "alarm", "type": "n.", "meaning": "chuông báo" }, { "word": "loudly", "type": "adv.", "meaning": "ồn ào" } ] },
  "q0483": { "translation": "Phần mềm mới rất đáng tin cậy.", "vocab": [ { "word": "software", "type": "n.", "meaning": "phần mềm" }, { "word": "reliable", "type": "adj.", "meaning": "đáng tin cậy" } ] },
  "q0484": { "translation": "Họ chứng minh lý thuyết đã sai.", "vocab": [ { "word": "prove", "type": "v.", "meaning": "chứng minh" }, { "word": "theory", "type": "n.", "meaning": "lý thuyết" } ] },
  "q0485": { "translation": "Công nhân đã dọn dẹp nhà kho.", "vocab": [ { "word": "clean", "type": "v.", "meaning": "dọn dẹp" }, { "word": "warehouse", "type": "n.", "meaning": "nhà kho" } ] },
  // Test 4
  "q0436": { "translation": "CEO đã duyệt ngân sách.", "vocab": [ { "word": "approve", "type": "v.", "meaning": "duyệt" }, { "word": "budget", "type": "n.", "meaning": "ngân sách" } ] },
  "q0437": { "translation": "Nhà cung cấp đã gọi hôm qua.", "vocab": [ { "word": "supplier", "type": "n.", "meaning": "nhà cung cấp" } ] },
  "q0438": { "translation": "Văn phòng mới trông rộng rãi.", "vocab": [ { "word": "spacious", "type": "adj.", "meaning": "rộng rãi" } ] },
  "q0439": { "translation": "Ủy ban đưa anh ấy lên làm chủ tịch.", "vocab": [ { "word": "committee", "type": "n.", "meaning": "ủy ban" }, { "word": "chairman", "type": "n.", "meaning": "chủ tịch" } ] },
  "q0440": { "translation": "Hàng hóa được giao nhanh chóng.", "vocab": [ { "word": "goods", "type": "n.", "meaning": "hàng hóa" }, { "word": "ship", "type": "v.", "meaning": "giao hàng" } ] },
  "q0441": { "translation": "Lễ tân đã trả lời điện thoại.", "vocab": [ { "word": "receptionist", "type": "n.", "meaning": "lễ tân" } ] },
  "q0442": { "translation": "Báo cáo tài chính rất chính xác.", "vocab": [ { "word": "financial report", "type": "n.", "meaning": "báo cáo tài chính" }, { "word": "accurate", "type": "adj.", "meaning": "chính xác" } ] },
  "q0443": { "translation": "Khóa đào tạo làm nhân viên tự tin.", "vocab": [ { "word": "training", "type": "n.", "meaning": "đào tạo" }, { "word": "confident", "type": "adj.", "meaning": "tự tin" } ] },
  "q0444": { "translation": "Chúng tôi đã ký hợp đồng.", "vocab": [ { "word": "sign", "type": "v.", "meaning": "ký" }, { "word": "contract", "type": "n.", "meaning": "hợp đồng" } ] },
  "q0445": { "translation": "Hệ thống sụp đổ đột ngột.", "vocab": [ { "word": "system", "type": "n.", "meaning": "hệ thống" }, { "word": "crash", "type": "v.", "meaning": "sụp đổ" } ] },
  "q0446": { "translation": "Chiến lược tiếp thị có vẻ thành công.", "vocab": [ { "word": "marketing strategy", "type": "n.", "meaning": "chiến lược tiếp thị" }, { "word": "successful", "type": "adj.", "meaning": "thành công" } ] },
  "q0447": { "translation": "Họ bổ nhiệm cô ấy làm quản lý.", "vocab": [ { "word": "appoint", "type": "v.", "meaning": "bổ nhiệm" }, { "word": "manager", "type": "n.", "meaning": "quản lý" } ] },
  "q0448": { "translation": "Khách hàng đã chấp nhận lời đề nghị.", "vocab": [ { "word": "client", "type": "n.", "meaning": "khách hàng" }, { "word": "accept", "type": "v.", "meaning": "chấp nhận" } ] },
  "q0449": { "translation": "Nhà máy vận hành trôi chảy.", "vocab": [ { "word": "factory", "type": "n.", "meaning": "nhà máy" }, { "word": "operate", "type": "v.", "meaning": "vận hành" } ] },
  "q0450": { "translation": "Vật liệu rất đắt đỏ.", "vocab": [ { "word": "materials", "type": "n.", "meaning": "vật liệu" }, { "word": "expensive", "type": "adj.", "meaning": "đắt đỏ" } ] },
  "q0451": { "translation": "Sự trì hoãn làm khách hàng phát điên.", "vocab": [ { "word": "delay", "type": "n.", "meaning": "sự chậm trễ" }, { "word": "crazy", "type": "adj.", "meaning": "điên rồ/bực mình" } ] },
  "q0452": { "translation": "Kỹ thuật viên đã sửa máy tính.", "vocab": [ { "word": "technician", "type": "n.", "meaning": "kỹ thuật viên" }, { "word": "fix", "type": "v.", "meaning": "sửa chữa" } ] },
  "q0453": { "translation": "Giá cổ phiếu đã giảm.", "vocab": [ { "word": "stock price", "type": "n.", "meaning": "giá cổ phiếu" }, { "word": "fall", "type": "v.", "meaning": "giảm xuống" } ] },
  "q0454": { "translation": "Bài thuyết trình rất ấn tượng.", "vocab": [ { "word": "presentation", "type": "n.", "meaning": "bài thuyết trình" }, { "word": "impressive", "type": "adj.", "meaning": "ấn tượng" } ] },
  "q0455": { "translation": "Quản lý giữ cho nhóm luôn có động lực.", "vocab": [ { "word": "keep", "type": "v.", "meaning": "giữ/duy trì" }, { "word": "motivated", "type": "adj.", "meaning": "có động lực" } ] },
  "q0456": { "translation": "Thư ký đã soạn lá thư.", "vocab": [ { "word": "type", "type": "v.", "meaning": "đánh máy" }, { "word": "letter", "type": "n.", "meaning": "lá thư" } ] },
  "q0457": { "translation": "Cuộc họp kết thúc sớm.", "vocab": [ { "word": "end", "type": "v.", "meaning": "kết thúc" }, { "word": "early", "type": "adv.", "meaning": "sớm" } ] },
  "q0458": { "translation": "Các quy tắc mới nghe có vẻ nghiêm ngặt.", "vocab": [ { "word": "rule", "type": "n.", "meaning": "quy tắc" }, { "word": "strict", "type": "adj.", "meaning": "nghiêm ngặt" } ] },
  "q0459": { "translation": "Họ bầu anh ấy làm tổng thống/chủ tịch.", "vocab": [ { "word": "vote", "type": "v.", "meaning": "bầu cử" }, { "word": "president", "type": "n.", "meaning": "chủ tịch/tổng thống" } ] },
  "q0460": { "translation": "Công ty đã mua máy tính xách tay mới.", "vocab": [ { "word": "company", "type": "n.", "meaning": "công ty" }, { "word": "laptop", "type": "n.", "meaning": "máy tính xách tay" } ] },
  // Test 3
  "q0411": { "translation": "Quản lý đã xem xét dữ liệu.", "vocab": [ { "word": "review", "type": "v.", "meaning": "xem xét" }, { "word": "data", "type": "n.", "meaning": "dữ liệu" } ] },
  "q0412": { "translation": "Lô hàng đã đến an toàn.", "vocab": [ { "word": "shipment", "type": "n.", "meaning": "lô hàng" }, { "word": "safely", "type": "adv.", "meaning": "an toàn" } ] },
  "q0413": { "translation": "Chính sách mới có vẻ hiệu quả.", "vocab": [ { "word": "policy", "type": "n.", "meaning": "chính sách" }, { "word": "effective", "type": "adj.", "meaning": "hiệu quả" } ] },
  "q0414": { "translation": "Hội đồng bổ nhiệm anh ấy làm giám đốc.", "vocab": [ { "word": "board", "type": "n.", "meaning": "hội đồng" }, { "word": "appoint", "type": "v.", "meaning": "bổ nhiệm" } ] },
  "q0415": { "translation": "Mức thuế đã tăng.", "vocab": [ { "word": "tax rate", "type": "n.", "meaning": "mức thuế" }, { "word": "increase", "type": "v.", "meaning": "tăng" } ] },
  "q0416": { "translation": "Các nhà phân tích đã kiểm tra báo cáo.", "vocab": [ { "word": "analyst", "type": "n.", "meaning": "nhà phân tích" }, { "word": "check", "type": "v.", "meaning": "kiểm tra" } ] },
  "q0417": { "translation": "Quy trình hải quan rất nghiêm ngặt.", "vocab": [ { "word": "customs process", "type": "n.", "meaning": "quy trình hải quan" }, { "word": "strict", "type": "adj.", "meaning": "nghiêm ngặt" } ] },
  "q0418": { "translation": "Sự chậm trễ làm khách hàng tức giận.", "vocab": [ { "word": "delay", "type": "n.", "meaning": "sự chậm trễ" }, { "word": "angry", "type": "adj.", "meaning": "tức giận" } ] },
  "q0419": { "translation": "Chúng tôi đã đặt táo tươi.", "vocab": [ { "word": "order", "type": "v.", "meaning": "đặt hàng" }, { "word": "fresh", "type": "adj.", "meaning": "tươi" } ] },
  "q0420": { "translation": "Kế hoạch hậu cần đã trở nên phức tạp.", "vocab": [ { "word": "logistics plan", "type": "n.", "meaning": "kế hoạch hậu cần" }, { "word": "complicated", "type": "adj.", "meaning": "phức tạp" } ] },
  "q0421": { "translation": "Nhà kho đã mở cửa sớm.", "vocab": [ { "word": "warehouse", "type": "n.", "meaning": "nhà kho" }, { "word": "open", "type": "v.", "meaning": "mở cửa" } ] },
  "q0422": { "translation": "Nhóm thấy hệ thống rất hữu ích.", "vocab": [ { "word": "find", "type": "v.", "meaning": "tìm thấy/nhận thấy" }, { "word": "system", "type": "n.", "meaning": "hệ thống" }, { "word": "useful", "type": "adj.", "meaning": "hữu ích" } ] },
  "q0423": { "translation": "Công ty đã cập nhật phần mềm.", "vocab": [ { "word": "update", "type": "v.", "meaning": "cập nhật" }, { "word": "software", "type": "n.", "meaning": "phần mềm" } ] },
  "q0424": { "translation": "Kết quả cuối cùng trông đầy hứa hẹn.", "vocab": [ { "word": "final result", "type": "n.", "meaning": "kết quả cuối cùng" }, { "word": "promising", "type": "adj.", "meaning": "đầy hứa hẹn" } ] },
  "q0425": { "translation": "Cuộc họp bắt đầu muộn.", "vocab": [ { "word": "start", "type": "v.", "meaning": "bắt đầu" }, { "word": "late", "type": "adv.", "meaning": "muộn" } ] },
  "q0426": { "translation": "Họ bầu người đàn ông làm tổng thống/chủ tịch.", "vocab": [ { "word": "elect", "type": "v.", "meaning": "bầu chọn" }, { "word": "president", "type": "n.", "meaning": "chủ tịch/tổng thống" } ] },
  "q0427": { "translation": "Kế toán đã tính toán chi phí.", "vocab": [ { "word": "accountant", "type": "n.", "meaning": "kế toán" }, { "word": "calculate", "type": "v.", "meaning": "tính toán" } ] },
  "q0428": { "translation": "Cuộc đàm phán thất bại hoàn toàn.", "vocab": [ { "word": "negotiation", "type": "n.", "meaning": "sự đàm phán" }, { "word": "fail", "type": "v.", "meaning": "thất bại" } ] },
  "q0429": { "translation": "Quản lý dự án vẫn lạc quan.", "vocab": [ { "word": "project manager", "type": "n.", "meaning": "quản lý dự án" }, { "word": "optimistic", "type": "adj.", "meaning": "lạc quan" } ] },
  "q0430": { "translation": "Người giám sát ca ngợi ý tưởng là tuyệt vời.", "vocab": [ { "word": "call", "type": "v.", "meaning": "gọi/ca ngợi" }, { "word": "brilliant", "type": "adj.", "meaning": "tuyệt vời/thông minh" } ] },
  "q0431": { "translation": "Công nhân bốc hàng lên xe tải.", "vocab": [ { "word": "worker", "type": "n.", "meaning": "công nhân" }, { "word": "load", "type": "v.", "meaning": "chất hàng" } ] },
  "q0432": { "translation": "Giá cả giảm đột ngột.", "vocab": [ { "word": "price", "type": "n.", "meaning": "giá cả" }, { "word": "drop", "type": "v.", "meaning": "giảm xuống" } ] },
  "q0433": { "translation": "Tài liệu có vẻ là thật.", "vocab": [ { "word": "document", "type": "n.", "meaning": "tài liệu" }, { "word": "authentic", "type": "adj.", "meaning": "xác thực/thật" } ] },
  "q0434": { "translation": "Cô ấy coi như công việc đã xong.", "vocab": [ { "word": "consider", "type": "v.", "meaning": "xem xét/coi là" }, { "word": "finish", "type": "v.", "meaning": "kết thúc" } ] },
  "q0435": { "translation": "Anh ấy trình bày chiến lược mới.", "vocab": [ { "word": "present", "type": "v.", "meaning": "trình bày" }, { "word": "strategy", "type": "n.", "meaning": "chiến lược" } ] },
  // Test 1 & 2
  "q0041": { "translation": "Con gà đã chạy mất.", "vocab": [] },
  "q0042": { "translation": "Cô ấy hát rất hay/đẹp.", "vocab": [] },
  "q0043": { "translation": "Chiếc xe trông có vẻ đắt tiền.", "vocab": [ { "word": "expensive", "type": "adj.", "meaning": "đắt tiền" } ] },
  "q0044": { "translation": "Lucy đã trở thành giáo viên.", "vocab": [ { "word": "become", "type": "v.", "meaning": "trở thành" }, { "word": "teacher", "type": "n.", "meaning": "giáo viên" } ] },
  "q0045": { "translation": "Anh ấy muốn một ít trà.", "vocab": [] },
  "q0046": { "translation": "Nhân viên hải quan kiểm tra lô hàng.", "vocab": [ { "word": "inspector", "type": "n.", "meaning": "người kiểm tra" }, { "word": "cargo", "type": "n.", "meaning": "hàng hóa" } ] },
  "q0047": { "translation": "Bà Brown mua cho con trai một ít bánh mì.", "vocab": [ { "word": "buy", "type": "v.", "meaning": "mua" }, { "word": "bread", "type": "n.", "meaning": "bánh mì" } ] },
  "q0048": { "translation": "Bạn làm tôi hạnh phúc.", "vocab": [] },
  "q0049": { "translation": "Họ thấy cô gái ấy thật thà.", "vocab": [ { "word": "find", "type": "v.", "meaning": "nhận thấy/tìm thấy" }, { "word": "honest", "type": "adj.", "meaning": "thật thà" } ] },
  "q0050": { "translation": "Bởi vì trời mưa to, chúng tôi đã ở nhà.", "vocab": [] },
  "q0051": { "translation": "Tất cả nhân viên phải mặc đồng phục.", "vocab": [ { "word": "employee", "type": "n.", "meaning": "nhân viên" }, { "word": "uniform", "type": "n.", "meaning": "đồng phục" } ] },
  "q0052": { "translation": "Chuyến bay đi Tokyo đã bị hoãn.", "vocab": [ { "word": "flight", "type": "n.", "meaning": "chuyến bay" }, { "word": "delay", "type": "n.", "meaning": "sự chậm trễ" } ] },
  "q0053": { "translation": "Điện thoại di động rất hữu ích.", "vocab": [ { "word": "mobile phone", "type": "n.", "meaning": "điện thoại di động" }, { "word": "useful", "type": "adj.", "meaning": "hữu ích" } ] },
  "q0054": { "translation": "Chúng tôi đã thay thế máy fax.", "vocab": [ { "word": "replace", "type": "v.", "meaning": "thay thế" }, { "word": "fax machine", "type": "n.", "meaning": "máy fax" } ] },
  "q0055": { "translation": "Tòa nhà văn phòng rất lớn.", "vocab": [ { "word": "office building", "type": "n.", "meaning": "tòa nhà văn phòng" }, { "word": "large", "type": "adj.", "meaning": "lớn" } ] },
  "q0056": { "translation": "Các bản đề xuất kinh doanh có vẻ hứa hẹn.", "vocab": [ { "word": "business proposal", "type": "n.", "meaning": "bản đề xuất kinh doanh" }, { "word": "promising", "type": "adj.", "meaning": "đầy hứa hẹn" } ] },
  "q0057": { "translation": "Người chơi trở thành trưởng nhóm.", "vocab": [ { "word": "player", "type": "n.", "meaning": "người chơi" }, { "word": "team leader", "type": "n.", "meaning": "trưởng nhóm" } ] },
  "q0058": { "translation": "Âm nhạc làm buổi biểu diễn thật ấn tượng.", "vocab": [ { "word": "music", "type": "n.", "meaning": "âm nhạc" }, { "word": "impressive", "type": "adj.", "meaning": "ấn tượng" } ] },
  "q0059": { "translation": "Tôi tìm thấy cuốn sách một cách dễ dàng.", "vocab": [ { "word": "find", "type": "v.", "meaning": "tìm thấy" }, { "word": "easily", "type": "adv.", "meaning": "một cách dễ dàng" } ] },
  "q0060": { "translation": "Ban quản lý sẽ thành lập một đội đặc nhiệm.", "vocab": [ { "word": "management", "type": "n.", "meaning": "ban quản lý" }, { "word": "special team", "type": "n.", "meaning": "đội đặc nhiệm" } ] },
  "q0061": { "translation": "Ông Anderson cần lời khuyên từ cấp trên.", "vocab": [ { "word": "advice", "type": "n.", "meaning": "lời khuyên" }, { "word": "supervisor", "type": "n.", "meaning": "người giám sát" } ] },
  "q0062": { "translation": "Hầu hết nhân viên tham gia cuộc thi.", "vocab": [ { "word": "employee", "type": "n.", "meaning": "nhân viên" }, { "word": "competition", "type": "n.", "meaning": "cuộc thi" } ] },
  "q0063": { "translation": "Bà Bacon là cố vấn tại bệnh viện.", "vocab": [ { "word": "consultant", "type": "n.", "meaning": "cố vấn" }, { "word": "hospital", "type": "n.", "meaning": "bệnh viện" } ] },
  "q0064": { "translation": "Các ứng viên nên đáp ứng các yêu cầu cho công việc.", "vocab": [ { "word": "candidate", "type": "n.", "meaning": "ứng viên" }, { "word": "qualification", "type": "n.", "meaning": "năng lực/trình độ" } ] },
  "q0065": { "translation": "Mỗi người tham gia được yêu cầu ký đơn đăng ký.", "vocab": [ { "word": "participant", "type": "n.", "meaning": "người tham gia" }, { "word": "application", "type": "n.", "meaning": "đơn đăng ký" } ] },
  "q0066": { "translation": "Nhân viên mới sẽ nhận được khóa đào tạo trong một tuần.", "vocab": [ { "word": "new employee", "type": "n.", "meaning": "nhân viên mới" }, { "word": "training", "type": "n.", "meaning": "đào tạo" } ] },
  "q0067": { "translation": "Tất cả nhân viên tham gia cuộc họp vào thứ Hai.", "vocab": [ { "word": "staff", "type": "n.", "meaning": "nhân viên" }, { "word": "meeting", "type": "n.", "meaning": "cuộc họp" } ] },
  "q0068": { "translation": "Máy móc sẽ đến vào ngày mai.", "vocab": [ { "word": "machine", "type": "n.", "meaning": "máy móc" }, { "word": "arrive", "type": "v.", "meaning": "đến" } ] },
  "q0069": { "translation": "Trang web cung cấp lời khuyên cho việc làm vườn.", "vocab": [ { "word": "advice", "type": "n.", "meaning": "lời khuyên" }, { "word": "gardening", "type": "n.", "meaning": "việc làm vườn" } ] },
  "q0070": { "translation": "Trung tâm thể hình Power Gym đã lắp đặt thiết bị mới.", "vocab": [ { "word": "equipment", "type": "n.", "meaning": "thiết bị" } ] }
};

let content = fs.readFileSync(targetFile, 'utf8');
const questionsData = eval(content.replace('window.questionsData =', ''));

questionsData.forEach(q => {
  if (ctcData[q.id]) {
    q.translation = ctcData[q.id].translation;
    q.core_vocabulary = ctcData[q.id].vocab;
  }
});

fs.writeFileSync(targetFile, 'window.questionsData = ' + JSON.stringify(questionsData, null, 2) + ';', 'utf8');
console.log('Successfully updated translation and vocabulary for 155 questions (Tests 1-7)!');
